// Generated by scripts/generate-droid-voice.py. Offsets are in seconds.
export const voiceBank = {
  "left": {
    "offset": 0.0,
    "duration": 0.476372,
    "caption": "Left flipper!"
  },
  "right": {
    "offset": 0.596372,
    "duration": 0.475556,
    "caption": "Right flipper!"
  },
  "both": {
    "offset": 1.191927,
    "duration": 0.554422,
    "caption": "Both flippers!"
  },
  "danger": {
    "offset": 1.866349,
    "duration": 0.49619,
    "caption": "Watch the drain!"
  },
  "ready": {
    "offset": 2.48254,
    "duration": 0.712154,
    "caption": "Ready to roll!"
  },
  "launch": {
    "offset": 3.314694,
    "duration": 0.501814,
    "caption": "Here we go!"
  },
  "whoa": {
    "offset": 3.936508,
    "duration": 0.223311,
    "caption": "Whoa!"
  },
  "ouch": {
    "offset": 4.279819,
    "duration": 0.853968,
    "caption": "Ow! My circuits!"
  },
  "ramp": {
    "offset": 5.253787,
    "duration": 0.482585,
    "caption": "Up we go!"
  },
  "bridge": {
    "offset": 5.856372,
    "duration": 0.818231,
    "caption": "Whee! Bridge time!"
  },
  "tunnel": {
    "offset": 6.794603,
    "duration": 1.055147,
    "caption": "Echo! Anybody home?"
  },
  "save": {
    "offset": 7.969751,
    "duration": 0.520499,
    "caption": "Nice save!"
  },
  "circuit": {
    "offset": 8.610249,
    "duration": 0.68966,
    "caption": "Circuit complete!"
  },
  "drain": {
    "offset": 9.419909,
    "duration": 1.010748,
    "caption": "Oh no! Not the drain!"
  },
  "over": {
    "offset": 10.550658,
    "duration": 0.661406,
    "caption": "One more orbit?"
  }
} as const;
export type VoiceKey = keyof typeof voiceBank;
