// Generated by scripts/generate-droid-beeps.py. Nonverbal clips; offsets in seconds.
export const voiceBank = {
  "left": {
    "offset": 0.0,
    "duration": 0.34,
    "caption": "Left flipper!"
  },
  "right": {
    "offset": 0.46,
    "duration": 0.409977,
    "caption": "Right flipper!"
  },
  "both": {
    "offset": 0.989977,
    "duration": 0.46,
    "caption": "Both flippers!"
  },
  "danger": {
    "offset": 1.569977,
    "duration": 0.489977,
    "caption": "Watch the drain!"
  },
  "ready": {
    "offset": 2.179955,
    "duration": 0.6,
    "caption": "[ready electronic beeps]"
  },
  "launch": {
    "offset": 2.899955,
    "duration": 0.510023,
    "caption": "[excited electronic chatter]"
  },
  "whoa": {
    "offset": 3.529977,
    "duration": 0.46,
    "caption": "[startled metallic yelp]"
  },
  "ouch": {
    "offset": 4.109977,
    "duration": 0.630023,
    "caption": "[pained electronic cry]"
  },
  "ramp": {
    "offset": 4.86,
    "duration": 0.66,
    "caption": "[rising excited burbles]"
  },
  "bridge": {
    "offset": 5.64,
    "duration": 0.690023,
    "caption": "[joyful electronic trill]"
  },
  "tunnel": {
    "offset": 6.450023,
    "duration": 0.850023,
    "caption": "[curious robot echoes]"
  },
  "save": {
    "offset": 7.420045,
    "duration": 0.510023,
    "caption": "[relieved electronic beeps]"
  },
  "circuit": {
    "offset": 8.050068,
    "duration": 0.8,
    "caption": "[triumphant beeps]"
  },
  "drain": {
    "offset": 8.970068,
    "duration": 0.610023,
    "caption": "[panicked electronic groan]"
  },
  "over": {
    "offset": 9.700091,
    "duration": 0.729977,
    "caption": "[wistful questioning burble]"
  }
} as const;
export type VoiceKey = keyof typeof voiceBank;
