"""Rebuild the original ORBIT robot voice sprite using FFmpeg + Flite.

Only the resulting WAV and its cue index ship with the game. No online speech
service or browser speech engine is used during play. Run from the repo root.
"""
import json
import subprocess
import tempfile
import wave
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SAMPLE_RATE = 22050
LINES = {
    "left": "Left flipper!",
    "right": "Right flipper!",
    "both": "Both flippers!",
    "danger": "Watch the drain!",
    "ready": "Ready to roll!",
    "launch": "Here we go!",
    "whoa": "Whoa!",
    "ouch": "Ow! My circuits!",
    "ramp": "Up we go!",
    "bridge": "Whee! Bridge time!",
    "tunnel": "Echo! Anybody home?",
    "save": "Nice save!",
    "circuit": "Circuit complete!",
    "drain": "Oh no! Not the drain!",
    "over": "One more orbit?",
}

with tempfile.TemporaryDirectory(prefix="orbit-voice-") as folder:
    folder = Path(folder)
    samples = bytearray()
    index = {}
    for name, line in LINES.items():
        text = folder / f"{name}.txt"
        text.write_text(line)
        output = folder / f"{name}.wav"
        # Pitch up a warm voice and add a restrained metallic overtone. Warnings
        # are shortened to leave room for the player to react, not queued later.
        tempo = 1.42 if name in {"left", "right", "both", "danger"} else 1.12
        filters = (
            "silenceremove=start_periods=1:start_duration=0.005:start_threshold=-42dB,"
            "areverse,silenceremove=start_periods=1:start_duration=0.005:start_threshold=-42dB,areverse,"
            f"asetrate=16000*1.23,aresample={SAMPLE_RATE},atempo={tempo},"
            "highpass=f=170,lowpass=f=6200,"
            "aecho=0.8:0.65:11:0.17,alimiter=limit=0.8:level=false,volume=0.82,"
            "afade=t=in:d=0.004,areverse,afade=t=in:d=0.004,areverse"
        )
        subprocess.run([
            "ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i",
            f"flite=textfile={text}:voice=slt", "-af", filters,
            "-ar", str(SAMPLE_RATE), "-ac", "1", "-c:a", "pcm_s16le", str(output)
        ], check=True)
        with wave.open(str(output)) as clip:
            data = clip.readframes(clip.getnframes())
        offset = len(samples) // 2 / SAMPLE_RATE
        duration = len(data) // 2 / SAMPLE_RATE
        index[name] = {"offset": round(offset, 6), "duration": round(duration, 6), "caption": line}
        samples.extend(data)
        samples.extend(b"\0\0" * round(SAMPLE_RATE * 0.12))

    (ROOT / "src/assets").mkdir(exist_ok=True)
    with wave.open(str(ROOT / "src/assets/droid-voice.wav"), "wb") as sprite:
        sprite.setnchannels(1)
        sprite.setsampwidth(2)
        sprite.setframerate(SAMPLE_RATE)
        sprite.writeframes(samples)
    (ROOT / "src/ui/voice-bank.ts").write_text(
        "// Generated by scripts/generate-droid-voice.py. Offsets are in seconds.\n"
        "export const voiceBank = " + json.dumps(index, indent=2) + " as const;\n"
        "export type VoiceKey = keyof typeof voiceBank;\n"
    )
    print(json.dumps({"bytes": len(samples) + 44, "clips": index}, indent=2))
