"""Build ORBIT's oscillator-only droid voice bank; no recordings or models.
MCP-Muse adaptation: see droid_synth.py and vendor/mcp-muse-LICENSE.
Run with Python 3's standard library. Only PCM and offsets ship at runtime.
"""
import hashlib
import json
import math
import struct
import wave
from pathlib import Path
from droid_synth import RATE, phrase, ring_tone, finish

ROOT = Path(__file__).resolve().parents[1]
# Stable warning rhythm is deliberately independent of expressive variants.
WARNINGS = {
    "left": [(0, .13, 440), (.18, .13, 370)],
    "right": [(0, .09, 630), (.13, .09, 715), (.26, .12, 800)],
    "both": [(0, .08, 440), (.11, .08, 680), (.22, .08, 440), (.33, .10, 680)],
    "danger": [(0, .12, 760), (.16, .12, 820), (.32, .14, 700)],
}
# emotion, total seconds, carrier Hz, syllable count; all three variants
# keep the same timing so random flavour cannot delay critical instructions.
RECIPES = {
    "ready": ("Affirmative", .60, 300, 3),
    "launch": ("Excited", .57, 420, 3),
    "whoa": ("Surprised", .46, 430, 2),
    "ouch": ("Negative", .56, 340, 2),
    "ramp": ("Curious", .66, 360, 3),
    "bridge": ("Happy", .69, 390, 4),
    "tunnel": ("Curious", .85, 280, 3),
    "save": ("Affirmative", .51, 330, 3),
    "circuit": ("Excited", .80, 440, 4),
    "drain": ("Worried", .61, 350, 3),
    "over": ("Sad", .73, 270, 2),
    "tap": ("Surprised", .23, 380, 1),
    "idle": ("Thoughtful", .68, 260, 3),
    "head-loss": ("Worried", .78, 390, 4),
}
CAPTIONS = {
    "left": "Left flipper!", "right": "Right flipper!",
    "both": "Both flippers!", "danger": "Watch the drain!",
    "ready": "[ready electronic beeps]", "launch": "[excited electronic chatter]",
    "whoa": "[startled electronic chirps]", "ouch": "[low electronic grumble]",
    "ramp": "[curious rising chatter]", "bridge": "[joyful electronic chatter]",
    "tunnel": "[curious robot echoes]", "save": "[relieved electronic beeps]",
    "circuit": "[triumphant beeps]", "drain": "[urgent worried chatter]",
    "over": "[sad descending burbles]", "tap": "[short electronic reaction]",
    "idle": "[curious electronic chatter]", "head-loss": "[confused electronic chatter]",
}


def render_warning(name):
    pulses = WARNINGS[name]
    samples = [0.0] * round((max(start + length for start, length, _ in pulses) + .03) * RATE)
    for start, length, base in pulses:
        packet = ring_tone(length, base / .72, 0, (0,), body=.72)
        onset = round(start * RATE)
        for i, value in enumerate(packet):
            samples[onset + i] += value
    return finish(samples, .58)


def pcm(samples):
    return b"".join(struct.pack("<h", round(v * 32767)) for v in samples)


def main():
    data = bytearray()
    index = {}
    metrics = {}
    preview_clips = {}
    for name in [*WARNINGS, *RECIPES]:
        variants = []
        count = 1 if name in WARNINGS else 3
        for variant in range(count):
            if name in WARNINGS:
                samples = render_warning(name)
            else:
                emotion, length, base, syllables = RECIPES[name]
                samples = finish(phrase(emotion, length, base * (1, .96, 1.035)[variant],
                    syllables, variant, echo=.22 if name == "tunnel" else 0))
            clip = {"offset": round(len(data) / 2 / RATE, 6), "duration": round(len(samples) / RATE, 6)}
            variants.append(clip)
            key = f"{name}:{variant}"
            metrics[key] = {"duration": clip["duration"], "rms": round(math.sqrt(sum(v*v for v in samples) / len(samples)), 5),
                            "peak": round(max(abs(v) for v in samples), 5), "sha256": hashlib.sha256(pcm(samples)).hexdigest()}
            data.extend(pcm(samples))
            data.extend(b"\0\0" * round(RATE * .10))
            if variant == 0 and name in ("idle", "whoa", "ouch", "bridge", "tunnel", "danger", "head-loss"):
                preview_clips[name] = samples
        index[name] = {**variants[0], "caption": CAPTIONS[name], "variants": variants}
    asset = ROOT / "src/assets/droid-beeps.wav"
    with wave.open(str(asset), "wb") as w:
        w.setparams((1, 2, RATE, 0, "NONE", "not compressed"))
        w.writeframes(data)
    (ROOT / "src/ui/voice-bank.ts").write_text(
        "// Generated by scripts/generate-droid-beeps.py. Oscillator-only droid clips.\n"
        "export const voiceBank = " + json.dumps(index, indent=2) + " as const;\n"
        "export type VoiceKey = keyof typeof voiceBank;\n")
    preview_path = ROOT / "public/audio/droid-voice-preview.wav"
    preview_path.parent.mkdir(parents=True, exist_ok=True)
    preview = []
    for name in ("idle", "whoa", "ouch", "bridge", "tunnel", "danger", "head-loss"):
        preview.extend(preview_clips[name])
        preview.extend([0.0] * round(RATE * .35))
    with wave.open(str(preview_path), "wb") as w:
        w.setparams((1, 2, RATE, 0, "NONE", "not compressed"))
        w.writeframes(pcm(preview))
    report = {"source": "Original oscillator audio using adapted MIT-licensed MCP-Muse code",
              "variants": sum(len(v["variants"]) for v in index.values()), "bytes": asset.stat().st_size,
              "sampleRate": RATE, "spriteSha256": hashlib.sha256(asset.read_bytes()).hexdigest(), "clips": metrics}
    (ROOT / "docs/validation/droid-voice-assets.json").write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps({k: v for k, v in report.items() if k != "clips"}, indent=2))


if __name__ == "__main__":
    main()
